function com_jlcm_prototipo_GwtDefinition(){var P='',xb='" for "gwt:onLoadErrorFn"',vb='" for "gwt:onPropertyErrorFn"',ib='"><\/script>',Z='#',ac='.cache.html',_='/',lb='//',Tb='3F915A8CE380CAB60AAC7301F4652D00',Wb='55F1B6AB7F8F1E610206788AF8DD489A',Xb='9A71EFA1FDF2458A6772E8B767330BBF',_b=':',Vb=':1',pb='::',nc='<script defer="defer">com_jlcm_prototipo_GwtDefinition.onInjectionDone(\'com.jlcm.prototipo.GwtDefinition\')<\/script>',hb='<script id="',jc='<script language="javascript" src="',sb='=',$='?',ub='Bad handler "',Yb='DE479E3788E953C69BF8BABBC90C56F7',hc='DOMContentLoaded',Zb='EC32CBAF63B58FA35EBDAC658FB384E1',$b='ED11B446059B44763F18A16DD8FB00B5',jb='SCRIPT',Ob='WebSocket',gb='__gwt_marker_com.jlcm.prototipo.GwtDefinition',kb='base',cb='baseUrl',T='begin',S='bootstrap',bb='clear.cache.gif',Q='com.jlcm.prototipo.GwtDefinition',eb='com.jlcm.prototipo.GwtDefinition.nocache.js',ob='com.jlcm.prototipo.GwtDefinition::',rb='content',Y='end',Sb='false',Kb='gecko',Lb='gecko1_8',U='gwt.codesvr=',V='gwt.hosted=',W='gwt.hybrid',bc='gwt/chrome/chrome.css',wb='gwt:onLoadErrorFn',tb='gwt:onPropertyErrorFn',qb='gwt:property',gc='head',Qb='hosted.html?com_jlcm_prototipo_GwtDefinition',fc='href',Jb='ie6',Ib='ie8',Hb='ie9',yb='iframe',ab='img',zb="javascript:''",cc='link',Pb='loadExternalRefs',mb='meta',Bb='moduleRequested',X='moduleStartup',Gb='msie',nb='name',Db='opera',Ab='position:absolute;width:0;height:0;border:none',dc='rel',Fb='safari',db='script',Rb='selectingPermutation',lc='soundmanager2-jsmin.js',mc='soundmanager2-jsmin.js"><\/script>',ic='soundmanager2-setup.js',kc='soundmanager2-setup.js"><\/script>',R='startup',ec='stylesheet',Ub='true',fb='undefined',Mb='unknown',Cb='user.agent',Nb='web.sockets',Eb='webkit';var m=window,n=document,o=m.__gwtStatsEvent?function(a){return m.__gwtStatsEvent(a)}:null,p=m.__gwtStatsSessionId?m.__gwtStatsSessionId:null,q,r,s,t=P,u={},v=[],w=[],x=[],y=0,z,A;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:T});if(!m.__gwt_stylesLoaded){m.__gwt_stylesLoaded={}}if(!m.__gwt_scriptsLoaded){m.__gwt_scriptsLoaded={}}function B(){var b=false;try{var c=m.location.search;return (c.indexOf(U)!=-1||(c.indexOf(V)!=-1||m.external&&m.external.gwtOnLoad))&&c.indexOf(W)==-1}catch(a){}B=function(){return b};return b}
function C(){if(q&&r){var b=n.getElementById(Q);var c=b.contentWindow;if(B()){c.__gwt_getProperty=function(a){return H(a)}}com_jlcm_prototipo_GwtDefinition=null;c.gwtOnLoad(z,Q,t,y);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Y})}}
function D(){function e(a){var b=a.lastIndexOf(Z);if(b==-1){b=a.length}var c=a.indexOf($);if(c==-1){c=a.length}var d=a.lastIndexOf(_,Math.min(c,b));return d>=0?a.substring(0,d+1):P}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=n.createElement(ab);b.src=a+bb;a=e(b.src)}return a}
function g(){var a=F(cb);if(a!=null){return a}return P}
function h(){var a=n.getElementsByTagName(db);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(eb)!=-1){return e(a[b].src)}}return P}
function i(){var a;if(typeof isBodyLoaded==fb||!isBodyLoaded()){var b=gb;var c;n.write(hb+b+ib);c=n.getElementById(b);a=c&&c.previousSibling;while(a&&a.tagName!=jb){a=a.previousSibling}if(c){c.parentNode.removeChild(c)}if(a&&a.src){return e(a.src)}}return P}
function j(){var a=n.getElementsByTagName(kb);if(a.length>0){return a[a.length-1].href}return P}
function k(){var a=n.location;return a.href==a.protocol+lb+a.host+a.pathname+a.search+a.hash}
var l=g();if(l==P){l=h()}if(l==P){l=i()}if(l==P){l=j()}if(l==P&&k()){l=e(n.location.href)}l=f(l);t=l;return l}
function E(){var b=document.getElementsByTagName(mb);for(var c=0,d=b.length;c<d;++c){var e=b[c],f=e.getAttribute(nb),g;if(f){f=f.replace(ob,P);if(f.indexOf(pb)>=0){continue}if(f==qb){g=e.getAttribute(rb);if(g){var h,i=g.indexOf(sb);if(i>=0){f=g.substring(0,i);h=g.substring(i+1)}else{f=g;h=P}u[f]=h}}else if(f==tb){g=e.getAttribute(rb);if(g){try{A=eval(g)}catch(a){alert(ub+g+vb)}}}else if(f==wb){g=e.getAttribute(rb);if(g){try{z=eval(g)}catch(a){alert(ub+g+xb)}}}}}}
function F(a){var b=u[a];return b==null?null:b}
function G(a,b){var c=x;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
function H(a){var b=w[a](),c=v[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(A){A(a,d,b)}throw null}
var I;function J(){if(!I){I=true;var a=n.createElement(yb);a.src=zb;a.id=Q;a.style.cssText=Ab;a.tabIndex=-1;n.body.appendChild(a);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:X,millis:(new Date).getTime(),type:Bb});a.contentWindow.location.replace(t+L)}}
w[Cb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(Db)!=-1}())return Db;if(function(){return b.indexOf(Eb)!=-1}())return Fb;if(function(){return b.indexOf(Gb)!=-1&&n.documentMode>=9}())return Hb;if(function(){return b.indexOf(Gb)!=-1&&n.documentMode>=8}())return Ib;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Jb;if(function(){return b.indexOf(Kb)!=-1}())return Lb;return Mb};v[Cb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};w[Nb]=function(){return Ob in window};v[Nb]={'false':0,'true':1};com_jlcm_prototipo_GwtDefinition.onScriptLoad=function(){if(I){r=true;C()}};com_jlcm_prototipo_GwtDefinition.onInjectionDone=function(){q=true;o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Pb,millis:(new Date).getTime(),type:Y});C()};E();D();var K;var L;if(B()){if(m.external&&(m.external.initModule&&m.external.initModule(Q))){m.location.reload();return}L=Qb;K=P}o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Rb});if(!B()){try{G([Db,Sb],Tb);G([Db,Ub],Tb);G([Db,Sb],Tb+Vb);G([Db,Ub],Tb+Vb);G([Jb,Sb],Wb);G([Jb,Ub],Wb);G([Jb,Sb],Wb+Vb);G([Jb,Ub],Wb+Vb);G([Lb,Sb],Xb);G([Lb,Ub],Xb);G([Lb,Sb],Xb+Vb);G([Lb,Ub],Xb+Vb);G([Fb,Sb],Yb);G([Fb,Ub],Yb);G([Fb,Sb],Yb+Vb);G([Fb,Ub],Yb+Vb);G([Ib,Sb],Zb);G([Ib,Ub],Zb);G([Ib,Sb],Zb+Vb);G([Ib,Ub],Zb+Vb);G([Hb,Sb],$b);G([Hb,Ub],$b);G([Hb,Sb],$b+Vb);G([Hb,Ub],$b+Vb);K=x[H(Cb)][H(Nb)];var M=K.indexOf(_b);if(M!=-1){y=Number(K.substring(M+1));K=K.substring(0,M)}L=K+ac}catch(a){return}}var N;function O(){if(!s){s=true;if(!__gwt_stylesLoaded[bc]){var a=n.createElement(cc);__gwt_stylesLoaded[bc]=a;a.setAttribute(dc,ec);a.setAttribute(fc,t+bc);n.getElementsByTagName(gc)[0].appendChild(a)}C();if(n.removeEventListener){n.removeEventListener(hc,O,false)}if(N){clearInterval(N)}}}
if(n.addEventListener){n.addEventListener(hc,function(){J();O()},false)}var N=setInterval(function(){if(/loaded|complete/.test(n.readyState)){J();O()}},50);o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:S,millis:(new Date).getTime(),type:Y});o&&o({moduleName:Q,sessionId:p,subSystem:R,evtGroup:Pb,millis:(new Date).getTime(),type:T});if(!__gwt_scriptsLoaded[ic]){__gwt_scriptsLoaded[ic]=true;document.write(jc+t+kc)}if(!__gwt_scriptsLoaded[lc]){__gwt_scriptsLoaded[lc]=true;document.write(jc+t+mc)}n.write(nc)}
com_jlcm_prototipo_GwtDefinition();